// Generated by CoffeeScript undefined
(function() {
  React.createClass({
    render: function() {
      return React.DOM.div({
        "single-quote-attr": 'value',
        "double-quote-attr": "value",
        "func-call": this.props.func(arg1, arg2, function() {
          return 1 + 1;
        }),
        "calculated-attr": this.props['prop-name'],
        "interpolated-attr": "CoffeeScript supports " + string.interpolation,
        "invalid-interpolated-attr": 'CoffeeScript supports #{string.interpolation}',
        "func-call": this.props.func(arg1, arg2),
        "anon-func-call": (function() {
          return 3;
        })(),
        "integers": 12345,
        "decimal": 123.45,
        "negative": -12345,
        "positive": +12345
      }, React.DOM.div({
        "single-quote-attr": 'value',
        "double-quote-attr": "value",
        "func-call": this.props.func(arg1, arg2, function() {
          return 1 + 1;
        }),
        "calculated-attr": this.props['prop-name'],
        "interpolated-attr": "CoffeeScript supports " + string.interpolation,
        "invalid-interpolated-attr": 'CoffeeScript supports #{string.interpolation}',
        "func-call": this.props.func(arg1, arg2),
        "anon-func-call": (function() {
          return 3;
        })(),
        "integers": 12345,
        "decimal": 123.45,
        "negative": -12345,
        "positive": +12345
      }, "test jsx text \u00a0 \x3E", this.props.func(arg1, arg2, function() {
        return 1 + 1;
      }), this.props['prop-name'], (function() {
        var five;
        return five = 3;
      })()), "test jsx text \u00a0 \x3E", this.props.func(arg1, arg2, function() {
        return 1 + 1;
      }), this.props['prop-name'], (function() {
        var five;
        return five = 3;
      })());
    }
  }, exports);

}).call(this);
